[package]
name = "swc_plugin_keep_export"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde ={ workspace = true }
fxhash= { workspace = true }
tracing = { workspace = true, features = ["release_max_level_info"] }
swc_core = { workspace = true, features = [
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
]}
swc_common = { workspace = true, features = ["concurrent"] }
serde_json = { workspace = true, features = ["unbounded_depth"]}
swc_plugin_macro = { workspace = true }
swc_plugin_proxy = { workspace = true }

[dev-dependencies]
testing = { workspace = true }
