[package]
name = "swc_plugin_keep_export"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = "1"
fxhash= "0.2.1"
easy-error = "1.0.0"
tracing="0.1.34"
swc_core = { version = "0.26.0", features = [
  "plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
]}
swc_common = { version = "0.28.10", features = ["concurrent"] }
serde_json = {version = "1", features = ["unbounded_depth"]}

[dev-dependencies]
testing="*"